# Generated by Django 2.0 on 2018-10-08 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events_etl', '0002_auto_20181008_1754'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='start_datetime',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='title',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
