# Generated by Django 2.0 on 2018-10-08 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events_etl', '0003_auto_20181008_1800'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_type',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
