# Generated by Django 2.0 on 2018-10-08 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events_etl', '0004_event_event_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaign',
            name='source_type',
        ),
        migrations.DeleteModel(
            name='Campaign',
        ),
        migrations.DeleteModel(
            name='EventSource',
        ),
    ]
