# -*- coding: utf-8 -*-
# Generated by Django 1.11a1 on 2018-10-11 04:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events_etl', '0005_auto_20181008_1813'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='visible',
            field=models.BooleanField(default=False),
        ),
    ]
